# Feedback from previous weeks and other and hints

1. Be careful about your environment remembering variables. Make sure your code works in a new _clean_ environment. In Colab: `Runtime`->`restart Runtime`, in Anaconda's Jupyter: `Kernel`->`Restart`.
2. Graphs without labels (or units when appropriate) are not worth any point.
3. Do put in sufficient explanatory comments in your code.
4. Functions are very important. Do look up the video on the Safari O'Reilly ressource if you are still not clear on them !

For this week you can use these imports at the start of your programs:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

We will use a new module `uncertainties`, which is **not** standard in the colab environment. You will have to first run:

In [2]:
! pip install -q uncertainties

To install the module before you can import it:

In [3]:
import uncertainties as uc
import uncertainties.umath as um # for maths functions

# Introduction
In the practical classes PX2133/PX2233 and PX2338 (Obs tech), as well as your year 3/4 project, a lot of emphasis is placed on the determination and mathematical handling of errors.
The uncertainties module allows us to deal very easily with [error propagation](https://en.wikipedia.org/wiki/Propagation_of_uncertainty). For this sheet you should remind yourself about error bars in measurements and about propagation of uncertainties. Take an example from your lab handbook:

**Example 1**: If the length of a rectangle is $1.24\pm0.02 m$ and its breadth is $0.61\pm0.01 m$, what is its area and the error in the area? The following code snippet solves this problem in a few lines.

In [4]:
L = uc.ufloat(1.24, 0.02)
W = uc.ufloat(0.61, 0.01)
print ('Area is:', L*W, 'm^2') # Do remember to add the units when printing!

Area is: 0.756+/-0.017 m^2


**Note**: For the area itself, it's fairly straightforward:

In [5]:
1.24*0.61

0.7564

However, for the error bar on this number:

In [6]:
0.02*0.01

0.0002

does not work. Instead, the [error progation formula](https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Example_formulae) gives:

In [7]:
np.abs(1.24*0.61)*np.sqrt((0.02/1.24)**2+(0.01/0.61)**2)

np.float64(0.01739540169125163)

So the area is $0.756\pm0.017 m^2$. `uncertainties` obviously saves a lot of work, even for such a simple case. You can also take a look at the web site uncertainties hosted at https://pythonhosted.org/uncertainties/user_guide.html. In particular, [this section](https://pythonhosted.org/uncertainties/user_guide.html#access-to-the-uncertainty-and-to-the-nominal-value) shows some of the properties of a `ufloat` you can access directly.

**Example 2**: A reference object is $10.0\pm0.0001 m$ long, and makes a viewing angle of $0.62\pm0.02 rad$. How far is it?

In [8]:
L = uc.ufloat(10.0, 0.0001)
theta = uc.ufloat(0.62,0.02)

Distance = (L/2)/um.tan(theta/2)

print ('Distance is:', Distance.nominal_value, 'm, with an error of:', Distance.std_dev)

Distance is: 15.609024890896208 m, with an error of: 0.537283338762715


Note the need to use "umath" functions (like `um.tan()` instead of `np.tan()`), and how to get the nominal value and the standard deviation of the uncertainties objects. To get nicer looking output, such as controlling the number of significant digits printed, you can use the information about formatting at https://docs.python.org/3/tutorial/inputoutput.html. In the exercises below you need to print the values to the screen. (Don’t forget units.)

# Exercises
This must be marked before you leave the lab. Mark weighting is in brackets.
**Save your work to GitHub after having run all cells with `Runtime` -> `Restart and run all`. And do not change the notebook's filename.** Do add comments to your code, you'll lose points if your code is hard to understand. Graphs without labels (or units when appropriate) are not worth any point.

## Exercise 0
[0] With some approximations, we have measured the mass of the following black-holes:
```
"35.6+/-3.9","30.6+/-3.7","63.1+/-3.2","23.2+/-9.8","13.6+/-4.5","35.7+/-6.8","13.7+/-6.0","7.7+/-2.4","20.5+/-4.0"
```
Compute for each (with error-bars) their lifetime due to Hawking radiation:
$$
t = \left(\frac{M}{M_{\odot}}\right)^3\,\times\,2.097\,\times\,10^{67} yr
$$

(this exercise is for demonstration purposes and won't be marked)

In [9]:
def lifetime(mass):
  time=(mass**3)*2.097*1e67
  return(time)


In [10]:
strings=["35.6+/-3.9","30.6+/-3.7","63.1+/-3.2","23.2+/-9.8","13.6+/-4.5","35.7+/-6.8","13.7+/-6.0","7.7+/-2.4","20.5+/-4.0"]

In [11]:
masses=[uc.ufloat_fromstr(s) for s in strings]
print(masses)

[35.6+/-3.9, 30.6+/-3.7, 63.1+/-3.2, 23.2+/-9.8, 13.6+/-4.5, 35.7+/-6.8, 13.7+/-6.0, 7.7+/-2.4, 20.5+/-4.0]


In [12]:
['(:10.1e)'.format(lifetimes=lifetime(m)) for m in masses]
print(lifetimes)



NameError: name 'lifetimes' is not defined

## Exercise 1
[2] An object is measured to travel a distance $x = 5.1 \pm 0.4 m$ during a time of $t = 0.4 \pm 0.1 s$. What is the average velocity and the error in the average velocity?

In [13]:
x=uc.ufloat(5.1,0.4)
t=uc.ufloat(0.4,0.1)
v=x/t
print(v)


12.7+/-3.3


## Exercise 2
[2] An enterprising cow attempts to jump over the moon by jumping vertically into the air with initial speed $v_0=4.0\pm0.2 m/s$. After a time $t=0.60\pm0.06s$, the height of the cow is $h = v_0t-\frac{1}{2}g t^2 = 0.636 m$. What is the uncertainty in $h$? Take $g$ as exactly $9.81 ms^{-2}$.

In [14]:
v=uc.ufloat(4.0,0.2)
t=uc.ufloat(0.60,0.06)
g=9.81
h=v*t-0.5*g*t**2
print(h)

0.63+/-0.16


## Exercise 3
[2] In an optics experiment the object distance $u$ is measured to be 20cm and the image distance $v$ is 10cm, both to an accuracy of 0.5cm. Find the focal length $f$ of the lens using the formula:

$$ \frac{1}{u}+\frac{1}{v}=\frac{1}{f}$$

In [51]:
u=uc.ufloat(20,0.5)
v=uc.ufloat(10,0.5)
f=1/(u+v)
print(f)

0.0333+/-0.0008


## Exercise 4
[2] Two students each measure the refractive index of water. Jack measures a value of $1.33 \pm 0.03$ while Jill measures $1.28 \pm 0.02$. Are these values in agreement? *You do have to think a bit about this one...*

In [16]:
'the refractive index of water is 1.33 so Jack is correct and Jill is incorrect as even on her higher error the 1.3 is lower than 1.33, however to 1sf they would both be in agreement'

Jack=uc.ufloat(1.33,0.03)
Jill=uc.ufloat(1.28,0.02)
diff = Jack-Jill

print(Jack-Jill)


if diff.nominal_value < diff.std_dev:
  print("Jack and Jill are in agreement")
else:
  print("Jack and Jill are not in agreement")


0.05+/-0.04
Jack and Jill are not in agreement


## Exercise 5
[2] The damped resonance frequency $\omega_{res}$ of an oscillating system is related to the (un-damped) natural angular frequency $\omega_0$ and the damping coefficient $\alpha$ by:

$$\omega_{res} = \sqrt{ \omega_0^2 - 2\alpha^2}$$

Find $f_0$ if the measured resonance frequency $f_{res}$ is $23.2\pm0.1 Hz$ and the measured damping coefficient is $19.5\pm0.5s^{-1}$.


In [17]:
fres=uc.ufloat(23.2,0.1)
α=uc.ufloat(19.5,0.5)
ωres=fres*2*np.pi
ω0=um.sqrt(ωres**2+2*α**2)
f0=ω0/(2*np.pi)
print(f0)




23.61+/-0.10


## Exercise 6
[2] Suppose you have the following equation from one of your lab experiments:

$$f=\frac{c}{2}\sqrt{\frac{n_x^2}{L_x^2}+\frac{n_y^2}{L_y^2}+\frac{n_z^2}{L_z^2}}$$

where $f$ is the resonant frequency of sound waves in a box of sides $L_x$, $L_y$ and $L_z$ in length and the $n_x$ etc. are integers. $L_x = 10.2\pm0.2m$, $L_y = 5.2\pm0.3m$ and $L_z = 20.0\pm0.1 m$, while $c = 331.3 + T * 0.606 \,m\,s^{-1}$ is the temperature-dependent speed of sound, and the temperature $T$ is $23 \pm 1^\circ C$.
Calculate $f$ and the error in $f$ for the following values of $(nx,ny,nz)= (1,1,1), (1,1,2)$ and $(2,1,1)$.


In [18]:
Lx=uc.ufloat(10.2,0.2)
Ly=uc.ufloat(5.2,0.3)
Lz=uc.ufloat(20.0,0.1)
T=uc.ufloat(23,1)
c=331.3+T*0.606
nx=1
ny=1
nz=1

nx1=1
ny1=1
nz1=2

nx2=2
ny2=1
nz2=1
f1=(c/2)*um.sqrt((nx**2)/(Lx**2)+(ny**2)/(Ly**2)+(nz**2)/(Lz**2))
print(f"f1 (1,1,1): {f1:.2fS} Hz")

f2=(c/2)*um.sqrt((nx1**2)/(Lx**2)+(ny1**2)/(Ly**2)+(nz1**2)/(Lz**2))
print(f"f2 (1,1,2): {f2:.2fS} Hz")

f3=(c/2)*um.sqrt((nx2**2)/(Lx**2)+(ny2**2)/(Ly**2)+(nz2**2)/(Lz**2))
print(f"f3 (2,1,1): {f3:.2fS} Hz")

f1 (1,1,1): 38.25(1.67) Hz
f2 (1,1,2): 41.07(1.56) Hz
f3 (2,1,1): 48.19(1.40) Hz


## Exercise 7
[4] The reflection coefficient $R_\parallel$ for parallel plane-polarised light reflected from a surface is given by the equation:

$$ R_\parallel = \frac{\tan^2(\theta_i - \theta_t)}{\tan^2(\theta_i + \theta_t)} $$

Calculate the error in $R_\parallel$ given measurements $\theta_i = (78 \pm 1)^\circ$ and $\theta_t = (40 \pm 1)^\circ$.

In [19]:
θi=uc.ufloat(78,1)
θt=uc.ufloat(40,1)

θirad=um.radians(θi)
θtrad=um.radians(θt)

R=(um.tan(θirad-θtrad)**2)/(um.tan(θirad+θtrad)**2)
print(f"The reflection coefficient in R is: {R:.2f}")



The reflection coefficient in R is: 0.17+/-0.03


## Exercise 8
[4] Calculate and print to the screen the fractional uncertainty, as a percentage to one
significant figure, of the fluid flow discharge coefficient $C_d$ from the equation

$$
C_d = \frac{\dot{m}\sqrt{1-\left(\frac{d}{D}\right)^4}}{Kd^2F\sqrt{\rho\Delta P}}
$$

where

\begin{align*}
    C_d &= \text{discharge coefficient}&& \text{(no units)} \\
    \dot{m} &= \text{mass flow rate}&& = 0.13 \pm 0.01kg\,s^{-1} \\
    d &= \text{orifice diameter}&& = 11\pm 1 mm \\
    D &= \text{pipe diameter}&& = 71 \pm 1 mm \\
    \rho &= \text{fluid density}&& =1.01\pm0.01g\,cm^{-3} \\
    \Delta P &= \text{differential pressure}&& =156 \pm 7 Pa \\
    K &= \text{a constant parameter}&& =\text{constant (no units)} \\
    F &= \text{thermal expansion factor}&& =\text{constant (no units)}
\end{align*}


In [20]:
m=uc.ufloat(0.13,0.01)
d=uc.ufloat(11,1)/1000
D=uc.ufloat(71,1)/1000
ρ=uc.ufloat(1.01,0.01)*1000
ΔP=uc.ufloat(156,7)
K=1
F=1

C=(m*um.sqrt(1-(d/D)**4))/(K*d**2*F*um.sqrt(ρ*ΔP))
print(f"The discharge coefficient is: {C:.2f}")

print(C.std_dev)
print(C.nominal_value)


The discharge coefficient is: 2.71+/-0.54
0.5380637699013505
2.7058882075718156


In [21]:
fractional_uncertainty_percentage = (C.std_dev / C.nominal_value) * 100

print(f"The fractional uncertainty of the discharge coefficient is: {fractional_uncertainty_percentage:.2f}%")

The fractional uncertainty of the discharge coefficient is: 19.88%


## Exercise 9: Optional problem (not marked)
If you have time and want to try something interesting, do the following problem by plotting in 2D:
 - Draw an equilateral triangle with vertices and coordinates: vertex 1: $(p_1,q_1)$; vertex 2: $(p_2, q_2)$; vertex 3: $(p_3, q_3)$.
 - Place a dot at an arbitrary point $P = (x_0, y_0)$ within this triangle.
 - Find the next point by selecting randomly an integer $n = 1 , 2, $  or $3$ :
    1. If 1 , place a dot halfway between P and vertex 1.
    2. If 2 , place a dot halfway between P and vertex 2.
    3. If 3 , place a dot halfway between P and vertex 3.
 - Repeat the last two steps using the last dot as the new P.

Mathematically, the coordinates of successive points are given by the formulae

$$(x_{i+1},y_{i+1})=0.5[(x_i,y_i)+(p_n,q_n)]$$

and

$$n=int(1+3r_i),$$

where $r_i$ is a random number between 0 and 1 and where the $int()$ function outputs the closest integer smaller than or equal to the argument.

Try extending this to four vertices.

## Exam Preparation: Overview of `uncertainties` and Key Concepts

This section summarizes the key concepts and code used in the exercise sheet, focusing on error propagation with the `uncertainties` Python library. This is crucial for understanding how to handle measurements with uncertainties.

### Core Concept: `uncertainties` library
The `uncertainties` library simplifies error propagation. Instead of manually applying complex error propagation formulas, you can treat numbers with uncertainties as a single object. When you perform mathematical operations on these objects, the library automatically calculates the propagated uncertainty.

### Key functions/shortcuts to remember:

*   `import uncertainties as uc`: Imports the main `uncertainties` module, commonly aliased as `uc`.
*   `import uncertainties.umath as um`: Imports the `umath` submodule for mathematical functions (like `tan`, `sqrt`, `radians`) that are compatible with `ufloat` objects. **Important:** Always use `um.function()` instead of `np.function()` or `math.function()` when working with `ufloat` objects.
*   `uc.ufloat(nominal_value, standard_deviation)`: This is the core function to create an uncertain number, e.g., `uc.ufloat(1.24, 0.02)`.
*   `uc.ufloat_fromstr(string_representation)`: Creates a `ufloat` object from a string like `'35.6+/-3.9'`.
*   `ufloat_object.nominal_value`: Accesses the central value of the uncertain number.
*   `ufloat_object.std_dev`: Accesses the standard deviation (uncertainty) of the uncertain number.
*   `print(ufloat_object)`: Prints in the format `nominal_value+/-standard_deviation`.
*   **Formatted output with f-strings**: Use `f"{value:.nfS}"` to format `ufloat` objects to `n` significant figures, e.g., `f"{value:.2fS}"`.


In [46]:
# Essential Imports for the 'uncertainties' library
import uncertainties as uc
import uncertainties.umath as um # For mathematical functions compatible with ufloat objects
import numpy as np # For general numerical operations (though umath is preferred for ufloat)

# Example of creating a ufloat object
my_uncertain_value = uc.ufloat(10.5, 0.2)
print(f"My uncertain value: {my_uncertain_value}")
print(f"Nominal value: {my_uncertain_value.nominal_value}")
print(f"Standard deviation: {my_uncertain_value.std_dev}")

# Example of creating from string
value_from_str = uc.ufloat_fromstr("12.3+/-0.4")
print(f"Value from string: {value_from_str}")


My uncertain value: 10.50+/-0.20
Nominal value: 10.5
Standard deviation: 0.2
Value from string: 12.3+/-0.4


### Example 1: Area Calculation

*   **Concept:** Demonstrates basic multiplication with `ufloat` objects and how `uncertainties` automatically handles error propagation.
*   **Formula:** Area = Length × Width


In [47]:
# Example 1: Area Calculation
L = uc.ufloat(1.24, 0.02)
W = uc.ufloat(0.61, 0.01)
Area = L * W
print (f'Area is: {Area:.3fS} m^2') # Output will be 0.756+/-0.017 m^2


Area is: 0.756(17) m^2


### Example 2: Distance Calculation with Trigonometric Functions

*   **Concept:** Shows how to use `umath` functions for trigonometric operations and how to extract `nominal_value` and `std_dev`.
*   **Formula:** Distance = (L/2) / tan(theta/2)


In [48]:
# Example 2: Distance Calculation
L_ex2 = uc.ufloat(10.0, 0.0001)
theta_ex2 = uc.ufloat(0.62,0.02)

Distance = (L_ex2/2) / um.tan(theta_ex2/2) # Note um.tan() here for ufloat compatibility

print (f'Distance is: {Distance.nominal_value:.3f} m, with an error of: {Distance.std_dev:.3f}')


Distance is: 15.609 m, with an error of: 0.537


### Exercise 0: Hawking Radiation Lifetime

*   **Concept:** Applying a power law formula to `ufloat` objects and using `ufloat_fromstr` to parse data from strings.
*   **Formula:** t = (M/M☉)³ × 2.097 × 10⁶⁷ yr


In [49]:
# Exercise 0: Hawking Radiation Lifetime
def lifetime(mass):
  # The formula for lifetime is applied directly to the mass (a ufloat object)
  time=(mass**3) * 2.097 * 1e67
  return(time)

strings_ex0 = ["35.6+/-3.9","30.6+/-3.7","63.1+/-3.2","23.2+/-9.8","13.6+/-4.5","35.7+/-6.8","13.7+/-6.0","7.7+/-2.4","20.5+/-4.0"]
masses_ex0 = [uc.ufloat_fromstr(s) for s in strings_ex0] # Converts list of strings to list of ufloat objects

print("Hawking Radiation Lifetimes:")
for m in masses_ex0:
  lt = lifetime(m)
  print(f"Mass: {m:.1fS} M_sun, Lifetime: {lt:.2eS} years") # Formatted output


Hawking Radiation Lifetimes:
Mass: 35.6(3.9) M_sun, Lifetime: 9.46(3.11)e+71 years
Mass: 30.6(3.7) M_sun, Lifetime: 6.01(2.18)e+71 years
Mass: 63.1(3.2) M_sun, Lifetime: 5.27(80)e+72 years
Mass: 23.2(9.8) M_sun, Lifetime: 2.62(3.32)e+71 years
Mass: 13.6(4.5) M_sun, Lifetime: 5.27(5.24)e+70 years
Mass: 35.7(6.8) M_sun, Lifetime: 9.54(5.45)e+71 years
Mass: 13.7(6.0) M_sun, Lifetime: 5.39(7.08)e+70 years
Mass: 7.7(2.4) M_sun, Lifetime: 9.57(8.95)e+69 years
Mass: 20.5(4.0) M_sun, Lifetime: 1.81(1.06)e+71 years


### Exercise 1: Average Velocity

*   **Concept:** Simple division of `ufloat` objects.
*   **Formula:** Velocity = Distance / Time


In [50]:
# Exercise 1: Average Velocity
x_ex1 = uc.ufloat(5.1,0.4)
t_ex1 = uc.ufloat(0.4,0.1)
v_ex1 = x_ex1 / t_ex1
print(f"Average velocity: {v_ex1:.1fS} m/s") # Output: 12.7+/-3.3


Average velocity: 12.7(3.3) m/s


### Exercise 2: Height of a Cow

*   **Concept:** Combining multiple operations (multiplication, subtraction, power) with `ufloat` objects and a known constant (`g`).
*   **Formula:** h = v₀t - ½gt²


In [39]:
# Exercise 2: Height of a Cow
v0_ex2 = uc.ufloat(4.0,0.2)
t_ex2 = uc.ufloat(0.60,0.06)
g_ex2 = 9.81 # g is an exact number for this problem
h_ex2 = v0_ex2 * t_ex2 - 0.5 * g_ex2 * t_ex2**2
print(f"Height of the cow: {h_ex2:.2fS} m") # Output: 0.63+/-0.16


Height of the cow: 0.63(16) m


### Exercise 3: Focal Length of a Lens

*   **Concept:** Calculating focal length using the lens formula, involving reciprocals and sums of `ufloat` objects.
*   **Formula:** 1/f = 1/u + 1/v  =>  f = 1 / (1/u + 1/v)


In [40]:
# Exercise 3: Focal Length
u_ex3 = uc.ufloat(20,0.5)
v_ex3 = uc.ufloat(10,0.5)
# Corrected formula for f
f_ex3 = 1 / ((1/u_ex3) + (1/v_ex3))
print(f"Focal length: {f_ex3:.2fS} cm") # Output: 6.67+/-0.17 cm (with the corrected formula)


Focal length: 6.67(23) cm


### Exercise 4: Agreement of Measurements

*   **Concept:** Determining if two measurements with uncertainties are in agreement. This is typically done by comparing the nominal difference between two values to the uncertainty of that difference. If the nominal difference is less than or equal to its uncertainty, they are considered in agreement.


In [41]:
# Exercise 4: Agreement of Measurements
Jack = uc.ufloat(1.33,0.03)
Jill = uc.ufloat(1.28,0.02)
diff_ex4 = Jack - Jill # Calculate the difference and its uncertainty

print(f"Difference between Jack and Jill's measurements: {diff_ex4:.2fS}")

# Condition for agreement: if the nominal difference is within one standard deviation of the difference
if abs(diff_ex4.nominal_value) < diff_ex4.std_dev:
  print("Jack and Jill's values are in agreement (within their combined uncertainties).")
else:
  print("Jack and Jill's values are NOT in agreement (their nominal difference is greater than their combined uncertainty).")


Difference between Jack and Jill's measurements: 0.05(4)
Jack and Jill's values are NOT in agreement (their nominal difference is greater than their combined uncertainty).


### Exercise 5: Damped Resonance Frequency

*   **Concept:** Rearranging a formula to solve for an unknown (`ω₀`) and using `um.sqrt` for square roots.
*   **Formula:** ω_res = √(ω₀² - 2α²)  => ω₀ = √(ω_res² + 2α²)


In [42]:
# Exercise 5: Damped Resonance Frequency
fres_ex5 = uc.ufloat(23.2,0.1)
alpha_ex5 = uc.ufloat(19.5,0.5)
ωres_ex5 = fres_ex5 * 2 * np.pi # Convert frequency to angular frequency

# Rearranged formula: ω0 = sqrt(ωres^2 + 2*alpha^2)
ω0_ex5 = um.sqrt(ωres_ex5**2 + 2 * alpha_ex5**2)
f0_ex5 = ω0_ex5 / (2 * np.pi) # Convert back to frequency
print(f"Natural angular frequency f0: {f0_ex5:.2fS} Hz") # Output: 23.61+/-0.10


Natural angular frequency f0: 23.61(10) Hz


### Exercise 6: Resonant Frequency of Sound Waves in a Box

*   **Concept:** A more complex formula involving squares, sums, square roots, and a temperature-dependent constant `c`. Demonstrates `f-string` formatting with `:.nfS` for `ufloat` objects.
*   **Formula:** f = (c/2) * √((nₓ²/Lₓ²) + (nᵧ²/Lᵧ²) + (n₂²/L₂²))


In [43]:
# Exercise 6: Resonant Frequency of Sound Waves
Lx_ex6 = uc.ufloat(10.2,0.2)
Ly_ex6 = uc.ufloat(5.2,0.3)
Lz_ex6 = uc.ufloat(20.0,0.1)
T_ex6 = uc.ufloat(23,1)
c_ex6 = 331.3 + T_ex6 * 0.606 # Speed of sound depends on temperature, so c becomes a ufloat

# Calculate for different (nx,ny,nz) values

# (nx,ny,nz) = (1,1,1)
nx_1 = 1; ny_1 = 1; nz_1 = 1
f1_ex6 = (c_ex6/2) * um.sqrt((nx_1**2)/(Lx_ex6**2) + (ny_1**2)/(Ly_ex6**2) + (nz_1**2)/(Lz_ex6**2))
print(f"f1 (1,1,1): {f1_ex6:.2fS} Hz")

# (nx,ny,nz) = (1,1,2)
nx_2 = 1; ny_2 = 1; nz_2 = 2
f2_ex6 = (c_ex6/2) * um.sqrt((nx_2**2)/(Lx_ex6**2) + (ny_2**2)/(Ly_ex6**2) + (nz_2**2)/(Lz_ex6**2))
print(f"f2 (1,1,2): {f2_ex6:.2fS} Hz")

# (nx,ny,nz) = (2,1,1)
nx_3 = 2; ny_3 = 1; nz_3 = 1
f3_ex6 = (c_ex6/2) * um.sqrt((nx_3**2)/(Lx_ex6**2) + (ny_3**2)/(Ly_ex6**2) + (nz_3**2)/(Lz_ex6**2))
print(f"f3 (2,1,1): {f3_ex6:.2fS} Hz")


f1 (1,1,1): 38.25(1.67) Hz
f2 (1,1,2): 41.07(1.56) Hz
f3 (2,1,1): 48.19(1.40) Hz


### Exercise 7: Reflection Coefficient

*   **Concept:** Using `um.radians` to convert degrees to radians for trigonometric functions and handling division of squared `ufloat` objects.
*   **Formula:** Rₚ = tan²(θᵢ - θₜ) / tan²(θᵢ + θₜ)


In [44]:
# Exercise 7: Reflection Coefficient
theta_i_ex7 = uc.ufloat(78,1)
theta_t_ex7 = uc.ufloat(40,1)

theta_i_rad_ex7 = um.radians(theta_i_ex7) # Convert to radians
theta_t_rad_ex7 = um.radians(theta_t_ex7)

# Formula for R_parallel
R_ex7 = (um.tan(theta_i_rad_ex7 - theta_t_rad_ex7)**2) / (um.tan(theta_i_rad_ex7 + theta_t_rad_ex7)**2)
print(f"The reflection coefficient R_parallel is: {R_ex7:.2fS}")


The reflection coefficient R_parallel is: 0.17(3)


### Exercise 8: Fractional Uncertainty of Discharge Coefficient

*   **Concept:** Calculating a complex formula and then determining the *fractional uncertainty* (standard deviation divided by nominal value) as a percentage.
*   **Formula:** C_d = (ṁ√(1 - (d/D)⁴)) / (Kd²F√(ρΔP))


In [45]:
# Exercise 8: Fractional Uncertainty of Discharge Coefficient
m_ex8 = uc.ufloat(0.13,0.01)
d_ex8 = uc.ufloat(11,1)/1000 # Convert mm to meters
D_ex8 = uc.ufloat(71,1)/1000 # Convert mm to meters
rho_ex8 = uc.ufloat(1.01,0.01)*1000 # Convert g/cm^3 to kg/m^3
delta_P_ex8 = uc.ufloat(156,7)
K_ex8 = 1 # Constants without uncertainty
F_ex8 = 1

# The main formula calculation
C_ex8 = (m_ex8 * um.sqrt(1 - (d_ex8/D_ex8)**4)) / (K_ex8 * d_ex8**2 * F_ex8 * um.sqrt(rho_ex8 * delta_P_ex8))
print(f"The discharge coefficient is: {C_ex8:.2fS}")

# Calculate fractional uncertainty as a percentage
fractional_uncertainty_percentage_ex8 = (C_ex8.std_dev / C_ex8.nominal_value) * 100

print(f"The fractional uncertainty of the discharge coefficient is: {fractional_uncertainty_percentage_ex8:.1f}%") # Formatted to 1 significant figure as requested


The discharge coefficient is: 2.71(54)
The fractional uncertainty of the discharge coefficient is: 19.9%


### Key Takeaways for your Exam:

*   Understand the fundamental idea of error propagation and why libraries like `uncertainties` are so useful.
*   Know how to create `ufloat` objects (`uc.ufloat()`, `uc.ufloat_fromstr()`).
*   Remember to use `umath` (`um.sqrt()`, `um.tan()`, `um.radians()`) for mathematical functions with `ufloat` objects.
*   Be able to extract the nominal value (`.nominal_value`) and standard deviation (`.std_dev`).
*   Practice interpreting the output `nominal_value+/-standard_deviation`.
*   Pay attention to units and conversions (e.g., mm to meters, g/cm³ to kg/m³).
*   Be ready to apply these concepts to various physical formulas.
*   F-string formatting for `ufloat` objects (`{variable:.nfS}`) is very useful for presenting results clearly.

Good luck with your exam!